import type { Request, Response, NextFunction } from 'express';
import { createRemoteJWKSet, jwtVerify, type JWTPayload } from 'jose';
import config from '../config/index.js';
import TokenService from '../auth/token.service.js';
import JWTService from '../auth/jwt.service.js';

let remoteJWKSet: ReturnType<typeof createRemoteJWKSet> | null = null;

if (config.auth.jwksUri) {
  try {
    remoteJWKSet = createRemoteJWKSet(new URL(config.auth.jwksUri));
  } catch (err) {
    console.warn('[auth] Invalid AUTH_JWKS_URI:', err);
  }
} else {
  console.warn('[auth] AUTH_JWKS_URI not set');
}

export interface ExtendedJWTPayload extends JWTPayload {
  userId?: string;
  email?: string;
  sessionId?: string;
  roles?: string[];
  deviceId?: string;
  deviceName?: string;
  deviceType?: string;
  ipAddress?: string;
  userAgent?: string;
}

export interface AuthRequest extends Request {
  user?: ExtendedJWTPayload;
}

function unauthorized(res: Response, message = 'Unauthorized') {
  res.status(401).json({ error: message });
}

export async function authMiddleware(
  req: AuthRequest,
  res: Response,
  next: NextFunction
): Promise<void> {
  try {
    const auth = (req.headers.authorization ?? '').trim();
    
    if (!auth || !auth.toLowerCase().startsWith('bearer ')) {
      unauthorized(res, 'Missing or invalid Authorization header');
      return;
    }
    
    const token = auth.slice(7).trim();
    
    // Try to verify with our JWT service first (for tokens generated by /auth/login)
    let payload: ExtendedJWTPayload | null = null;
    let verifiedWithLocal = false;
    
    try {
      payload = JWTService.verifyAccessToken(token) as ExtendedJWTPayload;
      verifiedWithLocal = true;
    } catch (localErr: any) {
      // If local verification fails, try JWKS (for external auth providers)
      if (remoteJWKSet) {
        try {
          const verifyOptions: Parameters<typeof jwtVerify>[2] = {};
          if (config.auth.audience) verifyOptions.audience = config.auth.audience;
          if (config.auth.issuer) verifyOptions.issuer = config.auth.issuer;

          const result = await jwtVerify(token, remoteJWKSet, verifyOptions);
          payload = result.payload as ExtendedJWTPayload;
        } catch (jwksErr: any) {
          console.warn('[auth] Token verification failed with both methods');
          unauthorized(res, 'Invalid token');
          return;
        }
      } else {
        // No JWKS configured and local verification failed
        console.warn('[auth] Token verify failed:', localErr?.message);
        unauthorized(res, 'Invalid token');
        return;
      }
    }
    
    if (!payload) {
      unauthorized(res, 'Invalid token');
      return;
    }
    
    // Check if token is blacklisted (only for locally generated tokens)
    if (verifiedWithLocal) {
      const isBlacklisted = await TokenService.isTokenBlacklisted(token);
      if (isBlacklisted) {
        unauthorized(res, 'Token has been revoked');
        return;
      }
    }
    
    req.user = payload;
    
    next();
  } catch (err: any) {
    console.warn('[auth] Unexpected error in auth middleware:', err?.message);
    unauthorized(res, 'Invalid token');
  }
}

export default authMiddleware;
